// try-catch-finallyの例
try {
  console.log("tryブロック")
} catch (err) {
  console.log("catchブロック")
} finally {
  console.log("finallyブロック")
}

// try-finallyの例
try {
  console.log("tryブロック")
} finally {
  console.log("finallyブロック")
}